language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t padvd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true padvd/react-test npm test

after_success:
  - docker build -t dockertje87/multi-client ./client
  - docker build -t dockertje87/multi-nginx ./nginx
  - docker build -t dockertje87/multi-server ./server
  - docker build -t dockertje87/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dockertje87d/multi-client
  - docker push dockertje87/multi-nginx
  - docker push dockertje87/multi-server
  - docker push dockertje87/multi-worker



